### ISSUE TITLE
테스트용 계정 만들기

### ISSUE THREAD

**Issue by kseong-sscc** [simplestepscc/BAKG#26]
admin 계정 외에, 일반회원과 그룹관리자 계정 만들기
각 계정 권한은 #25 완료하고 결정하기로 함.

**Comment by mi0best** [comment]
Roles 정의
 1)	Site User Role
       - Administrator : Full(complete) access to change everything.
       - Editor : Create/edit any post or page.( ID:testEditor/ PW:testEditor1 )
       - Author : Create/edit only the posts/page they authored.( ID:test Author /PW:test Author1 )
       - Contributor : Create rough drafts but cannot publish. ( ID:test Contributor /PW:test Contributor1 )
       - Subscriber : Cannot do anything.( ID:test Subscriber/ PW:test Subscriber1 )
         
2)	Forum Role
       - Keymaster
       - Moderator
       - Participant
       - Spectator
       - Blocked

**Comment by mi0best** [comment]
Test Use(Subscriber등록완료 => ID: testSub /PW : testSub1)
 - Subscriber는 미등록이었음.

**Comment by kseong-sscc** [comment]
모든 계정 로그인 되는 것 확인했습니다. 👍
