### ISSUE TITLE
[Blog] page layout design

### ISSUE THREAD

**Issue by kseong-sscc** [simplestepscc/BAKG#27]
- blog list view
- post view

**Comment by kseong-sscc** [comment]
@mi0best please review page 2 & 3
https://docs.google.com/presentation/d/1zostRFY_rZ34R0Wef6tmd9ri68eC1snbEBnMJ8c5EZw/edit#slide=id.g433cdff3af_0_0

**Comment by mi0best** [comment]
완료(페이지 확인요)

**Comment by kseong-sscc** [comment]
수고하셨습니다. :)
